### ISSUE TITLE
Error while using revgeo()

### ISSUE THREAD

**Issue by nutansahoo** [mhudecheck/revgeo#1]
I have to reverse geocode a large no. of latitudes and longitudes for a project. At first the function `revgeo()` worked just fine. reverse geocoded 100 pairs of latitudes and longitudes. But then it started to throw the following errors:
`df2<- revgeo(latitude = Delhi2$LATITUDE[201:205], longitude = Delhi2$LONGITUDE[201:2015], provider = "google", API = "AIzaSyCWkD...", output = "frame")
`
The above code gave the following error- #Error in returned_data$status : $ operator is invalid for atomic vectors
`revgeo(latitude = Delhi2$LATITUDE[201:210], longitude = Delhi2$LONGITUDE[201:210], provider = "google", output = "hash", item = "zip", API = "AIzaSyCWk...")
`
Error in returned_data$results[[1]] : subscript out of bounds
Delhi2 is name of dataframe and LATITUDE and LONGITUDE are names of columns which contain  latitudes and longitudes.
I can't figure out what the problem is, any help is appreciated!

**Comment by mhudecheck** [comment]
It looks like an error handling issue.  

I've updated the code in github, and it should hopefully work.  If you're still running into an issue, please forward the ten or so coordinates that are throwing the error and I'll see what's going on.
