### ISSUE TITLE
Photon changed data structure

### ISSUE THREAD

**Issue by marinereilly** [mhudecheck/revgeo#10]
It looks like photon changed the data structure at some point. 

house number, county, and zip code don't exist anymore
street is now name

Here's an example point with the new data structure:
{"features":[{"geometry":{"coordinates":[-77.76104,37.199408],"type":"Point"},"type":"Feature","properties":{"osm_id":19777861,"osm_type":"W","extent":[-77.763207,37.207363,-77.757497,37.192277],"country":"United States of America","osm_key":"highway","city":"Ammon","osm_value":"tertiary","name":"Cobbs Road","state":"Virginia"}}],"type":"FeatureCollection"}

**Comment by mhudecheck** [comment]
Thanks for the info. It looks like they also changed their API end point. This project is on the back burner for now, but when I can I'll update the code for the new structure.
