### ISSUE TITLE
Gets stuck after ~1000 requests

### ISSUE THREAD

**Issue by tim-jc** [mhudecheck/revgeo#11]
Super useful package - thank you. For some reason, I get to about 900 - 1000 revgeo requests (either photon or bing) and R crashes. I've got about 150000 points to process so am writing to .csv after every point I reverse geocode so I'm not losing data. I just have to restart R and run again every time.

**Comment by pietrocolombo** [comment]
i have the same issue, I use bing

**Comment by pietrocolombo** [comment]
it seems the problem occurs on mac, i tried it on windows and i didn't have this problem

**Comment by mhudecheck** [comment]
I'll check it tomorrow on my wife's Macbook.  I haven't been able to replicate on either Manjaro or Windows 10 so far.

**Comment by mhudecheck** [comment]
I haven't been able to replicate this issue. If anyone runs into it using macOS and R > 4.01, please reopen.
