### ISSUE TITLE
no update for site location 

### ISSUE THREAD

**Issue by ValentinJourne** [mhudecheck/revgeo#13]
Hi, I've recently use your function to obtain site location based on lat/long. But now I have no more details. 

I've put a message a stack : https://stackoverflow.com/questions/65020254/missing-details-with-revgeo-r-package
If for example you use 

`revgeo(longitude=-77.0229529, latitude=38.89283435, output='frame')`

The function provide no information (city not found etc)

**Comment by mhudecheck** [comment]
Photon updated their API endpoint a couple of months ago. 

If you uninstall the version on CRAN and install the latest version here, it should work.

```
# Load Dev Tools
library(devtools)

# Reinstall from Git
unload(revgeo)
remove.packages('revgeo')
install_github('mhudecheck/revgeo')

# Run Code
library(revgeo)
revgeo(-77.016472, 38.785026)
```
