### ISSUE TITLE
revgeo not working with Photon

### ISSUE THREAD

**Issue by MaherSaid** [mhudecheck/revgeo#14]
I've been trying to resolve this problem for over an hour, but something odd is happening when using Photon as the provider; e.g.:

```
> revgeo(longitude=-77.0229529, latitude=38.89283435)
[1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=-77.0229529&lat=38.89283435"
[[1]]
[1] "House Number Not Found Street Not Found, City Not Found, State Not Found, Postcode Not Found, Country Not Found"
```

However, if I access the data directly through a webbrowser, the data is there:

`{"features":[{"geometry":{"coordinates":[-77.022953,38.89283435],"type":"Point"},"type":"Feature","properties":{"osm_id":66418953,"extent":[-77.0235924,38.8932053,-77.0223136,38.892427],"country":"United States of America","city":"Washington","countrycode":"US","postcode":"20004","locality":"Penn Quarter","type":"house","osm_type":"W","osm_key":"tourism","housenumber":"700","street":"Pennsylvania Avenue Northwest","osm_value":"attraction","name":"US National Archives","state":"Washington, D.C."}}],"type":"FeatureCollection"}`

Not sure what the problem is.

**Comment by mhudecheck** [comment]
Hi MaherSaid,

Try reinstalling RevGeo from the github repository instead of CRAN. Photon
recently updated their API endpoint, and I haven't had the time to update
the version on CRAN.

Sincerely,
Mike

**Comment by MaherSaid** [comment]
Resolved! Thank you!
