### ISSUE TITLE
revgeo examples not working

### ISSUE THREAD

**Issue by verajosemanuel** [mhudecheck/revgeo#15]
Just installed and tested with the most simple example from documentation:

```
revgeo(-77.016472, 38.785026)
[1] "Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=-77.016472&lat=38.785026"
Warning in seq.default(along = url) :
   argumentos parcialmente correctos de 'along' a 'along.with'
Warning in rep(as.integer(len), length = length(str)) :
   argumentos parcialmente correctos de 'length' a 'length.out'
[[1]]
[1] "House Number Not Found Street Not Found, City Not Found, State Not Found, Postcode Not Found, Country Not Found"
```

**Comment by emily-noble** [comment]
I'm having the same issue.

**Comment by emily-noble** [comment]
@verajosemanuel If I use the installed R package from my mirror, it installs [version 0.15](https://repo.miserver.it.umich.edu/cran/), which was published in 2017 and doesn't work properly for me.

However, if I download and compile the source directly from github, it does work properly. To install from github I had to:
```
install.packages('devtools') # Install the devtools package
detach("package:revgeo", unload = TRUE) # Detach the package I had already installed; otherwise installing from github won't work
library(devtools)
install_github('mhudecheck/revgeo')
```

**Comment by joelmlevin** [comment]
Updating the package as described by @emily-noble fixed my problem! Thank you.

**Comment by mhudecheck** [comment]
This issue was fixed in code at the last update. I haven't gotten around to pushing it to CRAN yet. 

I'm going to mark this as closed.
