### ISSUE TITLE
incorrect url while running code

### ISSUE THREAD

**Issue by irahulroy** [mhudecheck/revgeo#17]
Hi,

when i run the function using the default provider "photon", all my results are NULL and when i check the url, it says:

"Getting geocode data from Photon: http://photon.komoot.de/reverse?lon=-122.9467&lat=45.56908"

I see the issue is with the ".de" in the url. It should be ".io". Can you please advise?

**Comment by kdschneider** [comment]
Hi @rroy09, 

I just ran into the same issue. If you take a look in the code here on github, the issue should be fixed. @mhudecheck commited the fix 9 months ago. Maybe CRAN was not updated (It wasn't, I checked.)?

I will try the github version and report back if that works. 

**Edit:**

Installing the package from Github works. Just run
    
    library(devtools)
    install_github('mhudecheck/revgeo')

**Comment by mhudecheck** [comment]
This library is more or less in maintenance-only mode while I finish up my doctorate. For now please use the Github version.
